const playstationImages = {
  TRIANGLE: require("../../assets/buttonImages/playstation/triangle.png"),
  CIRCLE: require("../../assets/buttonImages/playstation/circle.png"),
  X: require("../../assets/buttonImages/playstation/cross.png"),
  SQUARE: require("../../assets/buttonImages/playstation/square.png"),
  R1: require("../../assets/buttonImages/playstation/r1.png"),
  R2: require("../../assets/buttonImages/playstation/r2.png"),
  R: require("../../assets/buttonImages/playstation/r_stick.png"),
  R3: require("../../assets/buttonImages/playstation/r_stick_click.png"),
  L1: require("../../assets/buttonImages/playstation/l1.png"),
  L2: require("../../assets/buttonImages/playstation/l2.png"),
  L: require("../../assets/buttonImages/playstation/l_stick.png"),
  L3: require("../../assets/buttonImages/playstation/l_stick_click.png"),
  UP: require("../../assets/buttonImages/playstation/dpad_up.png"),
  DOWN: require("../../assets/buttonImages/playstation/dpad_down.png"),
  LEFT: require("../../assets/buttonImages/playstation/dpad_left.png"),
  RIGHT: require("../../assets/buttonImages/playstation/dpad_right.png"),
  OPTIONS: require("../../assets/buttonImages/playstation/options.png"),
  SHARE: require("../../assets/buttonImages/playstation/share.png"),
  TOUCHPAD: require("../../assets/buttonImages/playstation/touch_pad.png"),
};

const xboxImages = {
  A: require("../../assets/buttonImages/xbox/a.png"),
  B: require("../../assets/buttonImages/xbox/b.png"),
  X: require("../../assets/buttonImages/xbox/x.png"),
  Y: require("../../assets/buttonImages/xbox/y.png"),
  BACKALT: require("../../assets/buttonImages/xbox/back_alt.png"),
  BACK: require("../../assets/buttonImages/xbox/back.png"),
  STARTALT: require("../../assets/buttonImages/xbox/start_alt.png"),
  START: require("../../assets/buttonImages/xbox/start.png"),
  UP: require("../../assets/buttonImages/xbox/dpad_up.png"),
  DOWN: require("../../assets/buttonImages/xbox/dpad_down.png"),
  LEFT: require("../../assets/buttonImages/xbox/dpad_left.png"),
  RIGHT: require("../../assets/buttonImages/xbox/dpad_right.png"),
  R: require("../../assets/buttonImages/xbox/r_stick.png"),
  R3: require("../../assets/buttonImages/xbox/r_stick_click.png"),
  RT: require("../../assets/buttonImages/xbox/rt.png"),
  RB: require("../../assets/buttonImages/xbox/rb.png"),
  L: require("../../assets/buttonImages/xbox/l_stick.png"),
  L3: require("../../assets/buttonImages/xbox/l_stick_click.png"),
  LT: require("../../assets/buttonImages/xbox/lt.png"),
  LB: require("../../assets/buttonImages/xbox/lb.png"),
};

export { playstationImages, xboxImages };
